spring:
  profiles:
    active: default
  datasource:
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/Users/davidgvaliya/Desktop/Мак/Java/HomeworkStub/myBD
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
management:
  server:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"